development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: convus_reviews_<%= ENV.fetch("CONDUCTOR_WORKSPACE", "development") %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: convus_reviews
