default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: convus_reviews_development<%= ENV["CONDUCTOR_WORKSPACE_NAME"] %>

test:
  <<: *default
  database: convus_reviews_test<%= ENV["CONDUCTOR_WORKSPACE_NAME"] %><%= ENV["TEST_ENV_NUMBER"] %>

production:
  <<: *default
  database: convus_reviews_production
  username: convus_reviews
  password: <%= ENV["CONVUS_REVIEWS_DATABASE_PASSWORD"] %>
